export const FETCH_WEATHER = '@WEATHER/FETCH_WEATHER';
export const FETCH_WEATHER_SUCCESS = '@WEATHER/FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = '@WEATHER/FETCH_WEATHER_FAILURE';
export const CLEAR_WEATHER = '@WEATHER/CLEAR_WEATHER';

enum Types {
  FETCH_WEATHER,
  FETCH_WEATHER_SUCCESS,
  FETCH_WEATHER_FAILURE,
  CLEAR_WEATHER,
};

export default Types;
